language: python
python: 
  - '3.6'
  - '3.9' 
virtualenv:
  system_site_packages: true
install:
  - pip install ./src
script: causalEGM -input test/demo.csv -output_dir ./ -n_iter 100 -startoff 0 -batches_per_eval 50
