dataset: Semi_acic
output_dir: './'
v_dim: 177
z_dim: 20
z0_dim: 10
z1_dim: 3
z2_dim: 3
z3_dim: 4
lr: 0.0002
bs: 32
alpha: 10
beta: 10
gamma: 10
nb_batches: 50000
batches_per_eval: 500
g_d_freq: 5
g_units: [64,64,64,64,64]
e_units: [64,64,64,64,64]
f_units: [64,32,8]
h_units: [64,32,8]
dz_units: [64,32,8]
dv_units: [64,32,8]
binary_treatment: True
use_z_rec: True
use_v_gan: True