dataset: Semi_ihdp
output_dir: './'
v_dim: 25
z_dim: 10
z0_dim: 5
z1_dim: 2
z2_dim: 2
z3_dim: 1
lr: 0.0002
bs: 32
alpha: 10
beta: 10
gamma: 10
nb_batches: 50000
batches_per_eval: 200
g_d_freq: 5
g_units: [512,512,512,512,512]
e_units: [256,256,256,256,256]
f_units: [64,64,64,64,64]
h_units: [64,64,64,64,64]
dz_units: [128,128,128]
dv_units: [128,128,128]
binary_treatment: True
use_z_rec: False
use_v_gan: False