dataset: Sim_Hirano_Imbens
v_dim: 15
z_dim: 6
z0_dim: 1
z1_dim: 1
z2_dim: 1
z3_dim: 3
x_min: 0
x_max: 3
lr: 0.0002
bs: 32
alpha: 10
beta: 10
gamma: 10
nb_batches: 200000
train: True
binary_treatment: False