dataset: Sim_Assum4
output_dir: './'
v_dim: 50
z_dim: 13
z0_dim: 1
z1_dim: 1
z2_dim: 1
z3_dim: 10
x_min: -3
x_max: 3
lr: 0.0002
bs: 32
alpha: 10
beta: 10
gamma: 10
nb_batches: 200000
batches_per_eval: 200
g_d_freq: 5
g_units: [512,512,512,512,512]
e_units: [256,256,256,256,256]
f_units: [64,64,64,64,64]
h_units: [64,64,64,64,64]
dz_units: [128,128,128]
dv_units: [128,128,128]
binary_treatment: False
use_z_rec: False
use_v_gan: False