dataset: Sim_Colangelo
output_dir: './'
v_dim: 100
z0_dim: 5
z1_dim: 5
z2_dim: 5
z3_dim: 5
z_dims: [5,5,5,5]
x_min: -2
x_max: 2
lr: 0.0002
bs: 32
alpha: 10
beta: 10
gamma: 10
nb_batches: 20000
batches_per_eval: 1000
g_d_freq: 5
g_units: [64,64,64,64,64]
e_units: [64,64,64,64,64]
f_units: [64,64,64,64,64]
h_units: [64,64,64,64,64]
dz_units: [32,32,32]
dv_units: [32,32,32]
binary_treatment: False
use_z_rec: True
use_v_gan: False
save_model: False